name: Greetings & Closing (Forouzanfar)

on:
  schedule:
    # 06:00 تهران ≈ 02:30 UTC
    - cron: '30 2 * * *'
    # 22:30 تهران ≈ 19:00 UTC
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  greet:
    if: github.event.schedule == '30 2 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install jdatetime hijri-converter requests
      - name: Morning greeting (06:00 Tehran)
        env:
          MODE: 'greet'
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: '@Foorouzanfar'
          TIMEZONE: 'Asia/Tehran'
          HASHTAGS: '#صبح_بخیر #اقتصاد #صرافی_فروزانفر'
          CHANNEL_HANDLE: '@Foorouzanfar'
        run: python rates_cron.py

  close:
    if: github.event.schedule == '0 19 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install jdatetime hijri-converter requests
      - name: Night closing (22:30 Tehran)
        env:
          MODE: 'close'
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: '@Foorouzanfar'
          TIMEZONE: 'Asia/Tehran'
          HASHTAGS: '#پایان_معاملات #اقتصاد #صرافی_فروزانفر'
          CHANNEL_HANDLE: '@Foorouzanfar'
        run: python rates_cron.py
